image: node:10

include:
    - template: Code-Quality.gitlab-ci.yml

code_quality:
    artifacts:
        paths: [gl-code-quality-report.json]

# You specify the stages. Those are the steps that GitLab will go through
# Order matters.
stages:
    - install
    - build
    - quality
    - test

install:
    stage: install
    script:
        - npm install
    artifacts:
        name: "artifacts"
        untracked: true
        expire_in: 60 mins
        paths:
            - .npm/
            - node_modules/

build:
    stage: build
    script:
        - CI=false npm run build
    artifacts:
        paths:
            - build
        expire_in: 1 week
    dependencies:
        - install

linting:
    stage: quality
    script:
        - npm run lint
    dependencies:
        - install

test:
    stage: test
    script:
        - npm run test:coverage
    dependencies:
        - install
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        when: always
        paths:
            - coverage/lcov-report/index.html
        expire_in: 10 days
