export const STATUS_APPROVED = "approved";
export const STATUS_PENDING = "pending";

export const DOC_TYPE_OTHER = "other";

// Dashboard action types
export const FETCH_NOTIFICATIONS_START = "FETCH_NOTIFICATIONS_START";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILED = "FETCH_NOTIFICATIONS_FAILED";
export const DELETE_NOTIFICATIONS_START = "DELETE_NOTIFICATIONS_START";
export const DELETE_NOTIFICATIONS_SUCCESS = "DELETE_NOTIFICATIONS_SUCCESS";
export const DELETE_NOTIFICATIONS_FAILED = "DELETE_NOTIFICATIONS_FAILED";
export const CREATE_NOTIFICATION_LOG_START = "CREATE_NOTIFICATION_LOG_START";
export const CREATE_NOTIFICATION_LOG_SUCCESS =
  "CREATE_NOTIFICATION_LOG_SUCCESS";
export const CREATE_NOTIFICATION_LOG_FAILED = "CREATE_NOTIFICATION_LOG_FAILED";

// Invoices action types
export const CREATE_INVOICE_START = "CREATE_INVOICE_START";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_FAILED = "CREATE_INVOICE_FAILED";
export const CREATE_INVOICE_BATCH_START = "CREATE_INVOICE_BATCH_START";
export const CREATE_INVOICE_BATCH_SUCCESS = "CREATE_INVOICE_BATCH_SUCCESS";
export const CREATE_INVOICE_BATCH_FAILED = "CREATE_INVOICE_BATCH_FAILED";
export const LIST_INVOICES_START = "LIST_INVOICES_START";
export const LIST_INVOICES_SUCCESS = "LIST_INVOICES_SUCCESS";
export const LIST_INVOICES_FAILED = "LIST_INVOICES_FAILED";
export const SEARCH_INVOICES_START = "SEARCH_INVOICES_START";
export const SEARCH_INVOICES_SUCCESS = "SEARCH_INVOICES_SUCCESS";
export const SEARCH_INVOICES_FAILED = "SEARCH_INVOICES_FAILED";
export const RETRIEVE_INVOICE_START = "RETRIEVE_INVOICE_START";
export const RETRIEVE_INVOICE_SUCCESS = "RETRIEVE_INVOICE_SUCCESS";
export const RETRIEVE_INVOICE_FAILED = "RETRIEVE_INVOICE_FAILED";
export const UPDATE_INVOICE_START = "UPDATE_INVOICE_START";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";
export const UPDATE_INVOICE_FAILED = "UPDATE_INVOICE_FAILED";
export const LIST_MORE_INVOICES_START = "LIST_MORE_INVOICES_START";
export const LIST_MORE_INVOICES_SUCCESS = "LIST_MORE_INVOICES_SUCCESS";
export const LIST_MORE_INVOICES_FAILED = "LIST_MORE_INVOICES_FAILED";
export const SEARCH_MORE_INVOICES_START = "SEARCH_MORE_INVOICES_START";
export const SEARCH_MORE_INVOICES_SUCCESS = "SEARCH_MORE_INVOICES_SUCCESS";
export const SEARCH_MORE_INVOICES_FAILED = "SEARCH_MORE_INVOICES_FAILED";
export const DELETE_INVOICE_START = "DELETE_INVOICE_START";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAILED = "DELETE_INVOICE_FAILED";
export const PAY_INVOICE_START = "PAY_INVOICE_START";
export const PAY_INVOICE_SUCCESS = "PAY_INVOICE_SUCCESS";
export const PAY_INVOICE_FAILED = "PAY_INVOICE_FAILED";
export const ARCHIVE_INVOICE_SUCCESS = "ARCHIVE_INVOICE_SUCCESS";
export const ARCHIVE_INVOICE_START = "ARCHIVE_INVOICE_START";
export const ARCHIVE_INVOICE_FAILED = "ARCHIVE_INVOICE_FAILED";
export const GENERATE_INVOICE_SUCCESS = "GENERATE_INVOICE_SUCCESS";
export const GENERATE_INVOICE_START = "GENERATE_INVOICE_START";
export const GENERATE_INVOICE_FAILED = "GENERATE_INVOICE_FAILED";
export const BULK_ACTION_START = "BULK_ACTION_START";
export const BULK_ACTION_FAILED = "BULK_ACTION_FAILED";
export const BULK_ACTION_SUCCESS = "BULK_ACTION_SUCCESS";
export const DOWNLOAD_INVOICE_CSV_STARTED = "DOWNLOAD_INVOICE_CSV_STARTED";
export const DOWNLOAD_INVOICE_CSV_FAILED = "DOWNLOAD_INVOICE_CSV_FAILED";
export const DOWNLOAD_INVOICE_CSV_SUCCESS = "DOWNLOAD_INVOICE_CSV_SUCCESS";
export const INVOICE_SUMMARY_START = "INVOICE_SUMMARY_START";
export const INVOICE_SUMMARY_SUCCESS = "INVOICE_SUMMARY_SUCCESS";
export const INVOICE_SUMMARY_FAILED = "INVOICE_SUMMARY_FAILED";
export const SEARCH_PROJECTS_START = "SEARCH_PROJECTS_START";
export const SEARCH_PROJECTS_SUCCESS = "SEARCH_PROJECTS_SUCCESS";
export const SEARCH_PROJECTS_FAILED = "SEARCH_PROJECTS_FAILED";
export const SEARCH_MORE_PROJECTS_START = "SEARCH_MORE_PROJECTS_START";
export const SEARCH_MORE_PROJECTS_SUCCESS = "SEARCH_MORE_PROJECTS_SUCCESS";
export const SEARCH_MORE_PROJECTS_FAILED = "SEARCH_MORE_PROJECTS_FAILED";

// Projects Actions types
export const FETCH_PROJECT_START = "FETCH_PROJECT_START";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAILED = "FETCH_PROJECT_FAILED";
// Invites action types
export const GET_PENDING_INVITES_START = "GET_PENDING_INVITES_START";
export const GET_PENDING_INVITES_SUCCESS = "GET_PENDING_INVITES_SUCCESS";
export const GET_PENDING_INVITES_FAILED = "GET_PENDING_INVITES_FAILED";
export const GET_MORE_PENDING_INVITES_START = "GET_MORE_PENDING_INVITES_START";
export const GET_MORE_PENDING_INVITES_SUCCESS =
  "GET_MORE_PENDING_INVITES_SUCCESS";
export const GET_MORE_PENDING_INVITES_FAILED =
  "GET_MORE_PENDING_INVITES_FAILED";
export const INVITE_START = "INVITE_START";
export const INVITE_SUCCESS = "INVITE_SUCCESS";
export const INVITE_FAILED = "INVITE_FAILED";
export const DELETE_INVITE_START = "DELETE_INVITE_START";
export const DELETE_INVITE_SUCCESS = "DELETE_INVITE_SUCCESS";
export const DELETE_INVITE_FAILED = "DELETE_INVITE_FAILED";
